import fs from 'fs';
import { execSync } from 'child_process';
import path from 'path';

const CONFIG_PATH = 'C:\\Users\\youco\\AppData\\Roaming\\dockhosting-cli\\Config\\config.json';
const PROJECT_ID = '6a3cac0dacb3a6b6c3654e6e';
const DB_HOST = 'db-facturo-db-6a39a389';
const DB_USER = 'dbuser';
const DB_PASS = 'oBNmqqWb-nqJrPWdBa6RkMu1';
const DB_NAME = 'facturo-db';
const OUTPUT_FILE = './production_backup.sql';

async function main() {
    console.log('🔄 Starting Database Sync from Production...');
    
    // 1. Read Token
    if (!fs.existsSync(CONFIG_PATH)) {
        console.error('❌ You need to run `dock login` first!');
        process.exit(1);
    }
    const conf = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    const token = conf.token;
    if (!token) {
        console.error('❌ No token found. Run `dock login` first!');
        process.exit(1);
    }

    async function runInProd(command) {
        const res = await fetch(`https://api.dockhosting.dev/api/v1/projects/${PROJECT_ID}/exec`, {
            method: 'POST',
            headers: { 'Authorization': 'Bearer ' + token, 'Content-Type': 'application/json' },
            body: JSON.stringify({ command })
        });
        const data = await res.json();
        return (data.data || data).output || '';
    }

    async function execPhp(phpCode) {
        const escaped = phpCode.replace(/'/g, "'\\''");
        return await runInProd(`php -r '${escaped}' 2>&1`);
    }

    // 2. Fetch Tables
    console.log('📋 Getting list of tables...');
    const tablesRaw = await execPhp(`
$pdo=new PDO("mysql:host=${DB_HOST};dbname=${DB_NAME};charset=utf8mb4","${DB_USER}","${DB_PASS}",[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$tables=$pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
echo implode("\\n",$tables);
    `.trim());

    const tables = tablesRaw.trim().split('\n').filter(t => t.trim());
    console.log(`✅ Found ${tables.length} tables`);

    let fullSQL = `-- Production Backup of ${DB_NAME}\n-- Generated: ${new Date().toISOString()}\n\nSET FOREIGN_KEY_CHECKS=0;\nSET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';\nSET NAMES utf8mb4;\n\n`;

    // 3. Dump Data
    for (const table of tables) {
        process.stdout.write(`  ⏳ Dumping table: ${table}... `);
        
        const createSql = await execPhp(`
$pdo=new PDO("mysql:host=${DB_HOST};dbname=${DB_NAME};charset=utf8mb4","${DB_USER}","${DB_PASS}",[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$r=$pdo->query("SHOW CREATE TABLE \`${table}\`")->fetch(PDO::FETCH_NUM);
echo $r[1];
        `.trim());
        fullSQL += `DROP TABLE IF EXISTS \`${table}\`;\n${createSql};\n\n`;

        const countRaw = await execPhp(`
$pdo=new PDO("mysql:host=${DB_HOST};dbname=${DB_NAME};charset=utf8mb4","${DB_USER}","${DB_PASS}",[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
echo $pdo->query("SELECT COUNT(*) FROM \`${table}\`")->fetchColumn();
        `.trim());
        const rowCount = parseInt(countRaw.trim()) || 0;
        
        if (rowCount === 0) {
            fullSQL += `-- No data in ${table}\n\n`;
            console.log('0 rows');
            continue;
        }
        
        console.log(`${rowCount} rows`);

        const batchSize = 50;
        for (let offset = 0; offset < rowCount; offset += batchSize) {
            const dataResult = await execPhp(`
$pdo=new PDO("mysql:host=${DB_HOST};dbname=${DB_NAME};charset=utf8mb4","${DB_USER}","${DB_PASS}",[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$rows=$pdo->query("SELECT * FROM \`${table}\` LIMIT ${batchSize} OFFSET ${offset}")->fetchAll(PDO::FETCH_ASSOC);
if(!$rows){exit;}
$cols=array_keys($rows[0]);
$colStr="\`".implode("\`,\`",$cols)."\`";
$vals=[];
foreach($rows as $r){
  $v=array_map(function($x)use($pdo){return $x===null?'NULL':"'".$pdo->quote($x,PDO::PARAM_STR)."'";}, $r);
  $vals[]="(".implode(",",$v).")";
}
echo "INSERT INTO \`${table}\` ($colStr) VALUES\\n".implode(",\\n",$vals).";";
            `.trim());

            if (dataResult) {
                // Fix the double single-quotes generated by PHP PDO quote inside array_map
                let cleanSQL = dataResult
                    .replace(/\(''/g, "('")
                    .replace(/''\)/g, "')")
                    .replace(/('','')/g, "','")
                    .replace(/,''/g, ",'")
                    .replace(/'',/g, "',");
                fullSQL += cleanSQL + '\n\n';
            }
        }
    }
    fullSQL += `\nSET FOREIGN_KEY_CHECKS=1;\n`;

    // 4. Save file
    fs.writeFileSync(OUTPUT_FILE, fullSQL, 'utf8');
    console.log(`\n💾 Backup saved to: ${OUTPUT_FILE}`);

    // 5. Import locally
    console.log('📥 Importing to local database...');
    try {
        execSync(`php artisan tinker --execute="DB::unprepared(file_get_contents('production_backup.sql'));"`, { stdio: 'inherit' });
        console.log('🎉 Database successfully synchronized!');
    } catch (e) {
        console.error('❌ Failed to import local database.');
    }

    // 6. Synchronize Images
    console.log('\n🖼️ Synchronizing images...');
    const localProductsDir = path.join(process.cwd(), 'storage', 'app', 'public', 'products');
    if (!fs.existsSync(localProductsDir)) {
        fs.mkdirSync(localProductsDir, { recursive: true });
    }

    const filesRaw = await execPhp(`
$files = glob('/var/www/html/storage/app/public/products/*');
echo implode("\\n", $files);
    `.trim());

    const files = filesRaw.trim().split('\n').filter(f => f.trim() && f.includes('.'));
    if (files.length === 0) {
        console.log('   No images found on production.');
    } else {
        console.log(`   Found ${files.length} images on production.`);
        let downloaded = 0;
        for (const file of files) {
            const fileName = path.basename(file.trim());
            const localPath = path.join(localProductsDir, fileName);
            if (fs.existsSync(localPath)) {
                continue; // Skip already downloaded images to save time
            }
            process.stdout.write(`   Downloading ${fileName}... `);
            const b64 = await execPhp(`echo base64_encode(file_get_contents('${file.trim()}'));`);
            if (b64 && !b64.includes('Fatal error')) {
                fs.writeFileSync(localPath, Buffer.from(b64.trim(), 'base64'));
                console.log('✅');
                downloaded++;
            } else {
                console.log('❌ Failed');
            }
        }
        console.log(`🎉 Downloaded ${downloaded} new images.`);
    }
}

main();
